export {default as Hero} from './hero.component.pug'
export {default as Process} from './process.component.pug'
export {default as AdvancedGrowth} from './advanced-growth.component.pug'
export {default as Building} from './building.component.pug'
export {default as Implementation} from './implementation.component.pug'
