export {default as Hero} from './hero.component.pug'
export {default as Process} from './process.component.pug'
export {default as AdvancedGrowth} from './advanced-growth.component.pug'
export {default as Building} from './building.component.pug'
export {default as Implementation} from './implementation.component.pug'
export {default as Team} from './team.component.pug'
export {default as Services} from './services.component.pug'
export {default as Contact} from './contact.component.pug'
